version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/trader_monitor
      - JWT_SECRET=supersecret
      - OPENAI_API_KEY=changeme
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules

volumes:
  mongo_data:
  node_modules:
